name: Rotki Packaging
on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.9.13
  NODE_VERSION: 16
  PYTHON_MACOS: 10.9
  PIP_VERSION: 22.1.2

jobs:
  create_draft:
    name: Create Draft
    runs-on: ubuntu-18.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Generate changelog
        id: change_log
        run: |
          version=$(echo $RELEASE_VERSION | sed 's/^v//g')
          changes=$(python3 tools/scripts/generate_changelog.py -f docs/changelog.rst -v $version)
          changes="${changes//'%'/'%25'}"
          changes="${changes//$'\n'/'%0A'}"
          changes="${changes//$'\r'/'%0D'}"
          echo "::set-output name=changes::$changes"
          echo "::set-output name=version::$version"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Rotki ${{ env.RELEASE_VERSION }} -
          body: |
            # Description

            For more information check the detailed changelog below :point_down:

            # Downloads

            Upgrade is highly recommended. Download the binary for your OS from below:

            - **Linux**
              - [AppImage](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-linux_x86_64-${{ env.RELEASE_VERSION }}.AppImage)
              - [Tar with executable](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-linux_x64-${{ env.RELEASE_VERSION }}.tar.xz)
              - [deb package](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-linux_amd64-${{ env.RELEASE_VERSION }}.deb)
              - [Standalone Backend](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotkehlchen-${{ steps.change_log.outputs.version }}-linux)
            - **OSX**
              - [DMG](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-darwin_x64-${{ env.RELEASE_VERSION }}.dmg)
              - [ZIP](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-darwin_x64-${{ env.RELEASE_VERSION }}.zip)
              - [Standalone Backend](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotkehlchen-backend-${{ steps.change_log.outputs.version }}-macos.zip)
            - **Windows**
              - [Windows executable](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-win32_x64-${{ env.RELEASE_VERSION }}.exe)
              - [Standalone Backend](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotkehlchen-${{ steps.change_log.outputs.version }}-windows.exe)
            
            Optionally, you can also [verify the integrity](https://rotki.readthedocs.io/en/latest/installation_guide.html#verifying-integrity) of the aforementioned binaries using the following checksums:
            
            - **Linux**
              - [AppImage checksum](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-linux_x86_64-${{ env.RELEASE_VERSION }}.AppImage.sha512)
              - [Tar with executable checksum](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-linux_x64-${{ env.RELEASE_VERSION }}.tar.xz.sha512)
              - [deb package](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-linux_amd64-${{ env.RELEASE_VERSION }}.deb.sha512)
              - [Standalone Backend](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotkehlchen-${{ steps.change_log.outputs.version }}-linux.sha512)
            - **OSX**
              - [DMG checksum](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-darwin_x64-${{ env.RELEASE_VERSION }}.dmg.sha512)
              - [ZIP checksum](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-darwin_x64-${{ env.RELEASE_VERSION }}.zip.sha512)
              - [Standalone Backend](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotkehlchen-backend-${{ steps.change_log.outputs.version }}-macos.zip.sha512)
            - **Windows**
              - [Windows executable checksum](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotki-win32_x64-${{ env.RELEASE_VERSION }}.exe.sha512)
              - [Standalone Backend](https://github.com/rotki/rotki/releases/download/${{ env.RELEASE_VERSION }}/rotkehlchen-${{ steps.change_log.outputs.version }}-windows.exe.sha512)

            # Release Highlights
            ----

            These were the highlights. Check below for the full changelog :point_down:

            ${{ steps.change_log.outputs.changes }}

            # Newly supported assets

            Added support for the following assets:

          draft: true
  linux:
    name: 'Build linux binary'
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-18.04
    needs: create_draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Cache cypress
        uses: actions/cache@v3
        with:
          path: ~/cache/Cypress
          key: ${{ runner.os }}-node--packaging-${{ hashFiles('frontend/package-lock.json') }}
      - name: Package
        id: packaging
        run: |
          npm install -g npm@8
          ./package.sh
      - name: Upload AppImage sha512 checksum file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.binary_checksum }}
          asset_name: ${{ steps.packaging.outputs.binary_checksum_name }}
          asset_content_type: text/plain
      - name: Upload tar sha512 checksum file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.archive_checksum }}
          asset_name: ${{ steps.packaging.outputs.archive_checksum_name }}
          asset_content_type: text/plain
      - name: Upload deb sha512 checksum file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.deb_checksum }}
          asset_name: ${{ steps.packaging.outputs.deb_checksum_name }}
          asset_content_type: text/plain
      - name: Upload backend binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.backend_binary }}
          asset_name: ${{ steps.packaging.outputs.backend_binary_name }}
          asset_content_type: application/octet-stream
      - name: Upload backend binary checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.backend_binary_checksum }}
          asset_name: ${{ steps.packaging.outputs.backend_binary_checksum_name }}
          asset_content_type: text/plain

  macos:
    name: 'Build macOS binary'
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment: macos_sign
    runs-on: macos-10.15
    needs: create_draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache python pkg
        uses: actions/cache@v3
        with:
          path: ~/python*.pkg
          key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ env.PYTHON_MACOS }}
      - name: Set up python
        run: packaging/setup-macos-python.sh ${{ env.PYTHON_VERSION }} ${{ env.PYTHON_MACOS }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Cache cypress
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/Cypress
          key: ${{ runner.os }}-node--packaging-${{ hashFiles('frontend/package-lock.json') }}
      - name: Package
        id: packaging
        run: |
          pip3 install --upgrade pip==${{ env.PIP_VERSION }}
          pip3 install virtualenv
          python3 -m virtualenv ~/venv
          source ~/venv/bin/activate
          npm install -g npm@8
          ./package.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CSC_KEY_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          IDENTITY: ${{ secrets.IDENTITY }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      - name: Upload dmg sha512 checksum file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.binary_checksum }}
          asset_name: ${{ steps.packaging.outputs.binary_checksum_name }}
          asset_content_type: text/plain
      - name: Upload zip sha512 checksum file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.archive_checksum }}
          asset_name: ${{ steps.packaging.outputs.archive_checksum_name }}
          asset_content_type: text/plain
      - name: Upload backend binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.backend_binary }}
          asset_name: ${{ steps.packaging.outputs.backend_binary_name }}
          asset_content_type: application/zip
      - name: Upload backend binary checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.backend_binary_checksum }}
          asset_name: ${{ steps.packaging.outputs.backend_binary_checksum_name }}
          asset_content_type: text/plain

  windows:
    name: 'Build windows binary'
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_DEPENDENCIES: "build-dependencies"
    runs-on: windows-latest
    needs: create_draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Cache Cypress
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\Cypress
          key: ${{ runner.os }}-node--packaging-${{ hashFiles('frontend/package-lock.json') }}
      - name: Persist Build Dependencies
        uses: actions/cache@v3
        with:
          path: ~\${{ env.BUILD_DEPENDENCIES }}\
          key: ${{ runner.os }}-build-dependencies
      - name: Build rotki
        id: packaging
        run: |
          npm install -g npm@8
          pip3 install --upgrade pip==${{ env.PIP_VERSION }}
          .\package.ps1
        shell: powershell
      - name: Upload exe sha512 checksum file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.binary_checksum }}
          asset_name: ${{ steps.packaging.outputs.binary_checksum_name }}
          asset_content_type: text/plain
      - name: Upload backend binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.backend_binary }}
          asset_name: ${{ steps.packaging.outputs.backend_binary_name }}
          asset_content_type: application/octet-stream
      - name: Upload backend binary checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_draft.outputs.upload_url }}
          asset_path: ${{ steps.packaging.outputs.backend_binary_checksum }}
          asset_name: ${{ steps.packaging.outputs.backend_binary_checksum_name }}
          asset_content_type: text/plain

  docker:
    name: 'Build docker image'
    runs-on: ubuntu-18.04
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Rotki Version
        id: rotki_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/*/}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            rotki/rotki:latest
            rotki/rotki:${{ steps.rotki_version.outputs.version }}
          build-args: |
            REVISION=${{ github.sha }}
            ROTKI_VERSION=${{ steps.rotki_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
