name: Rotki Nightly Builds

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.9.13
  NODE_VERSION: 16
  PYTHON_MACOS: 10.9
  PIP_VERSION: 22.1.2

jobs:
  build-linux:
    name: Build linux binary
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Cache cypress
        uses: actions/cache@v3
        with:
          path: ~/cache/Cypress
          key: ${{ runner.os }}-node--packaging-${{ hashFiles('frontend/package-lock.json') }}
      - name: Package
        id: packaging
        run: |
          npm install -g npm@8
          pip3 install --upgrade pip==${{ env.PIP_VERSION }}
          ./package.sh
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: nightly-linux
          path: |
            ${{ steps.packaging.outputs.binary }}
            ${{ steps.packaging.outputs.binary_checksum }}
      - name: Notify On Failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url ${{ secrets.WEBHOOK }} \
            --header 'Content-Type: application/json' \
            --data '{
          	"content": ":construction_site: **Github Actions:** ${{ github.job }} failed :x: \r\n\r\n  <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          }'


  build-macos:
    name: 'Build macOS binary'
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment: macos_sign
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache python pkg
        uses: actions/cache@v3
        with:
          path: ~/python*.pkg
          key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-${{ env.PYTHON_MACOS }}
      - name: Set up python
        run: packaging/setup-macos-python.sh ${{ env.PYTHON_VERSION }} ${{ env.PYTHON_MACOS }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Cache cypress
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/Cypress
          key: ${{ runner.os }}-node--packaging-${{ hashFiles('frontend/package-lock.json') }}
      - name: Package
        id: packaging
        run: |
          pip3 install --upgrade pip==${{ env.PIP_VERSION }}
          pip3 install virtualenv
          python3 -m virtualenv ~/venv
          source ~/venv/bin/activate
          npm install -g npm@8
          ./package.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CSC_KEY_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          IDENTITY: ${{ secrets.IDENTITY }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: nightly-macos
          path: |
            ${{ steps.packaging.outputs.binary }}
            ${{ steps.packaging.outputs.binary_checksum }}
      - name: Notify On Failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url ${{ secrets.WEBHOOK }} \
            --header 'Content-Type: application/json' \
            --data '{
          	"content": ":construction_site: **Github Actions:** ${{ github.job }} failed :x: \r\n\r\n  <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          }'

  build-windows:
    name: Build windows binary
    env:
      CI: true
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_DEPENDENCIES: "build-dependencies"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Cache cypress
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\Cypress
          key: ${{ runner.os }}-node--packaging-${{ hashFiles('frontend/package-lock.json') }}
      - name: Persist Build Dependencies
        uses: actions/cache@v3
        with:
          path: ~\${{ env.BUILD_DEPENDENCIES }}\
          key: ${{ runner.os }}-build-dependencies
      - name: Build rotki
        id: packaging
        run: |
          npm install -g npm@8
          pip3 install --upgrade pip==${{ env.PIP_VERSION }}
          .\package.ps1
        shell: powershell
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: nightly-windows
          path: |
            ${{ steps.packaging.outputs.binary }}
            ${{ steps.packaging.outputs.binary_checksum }}
      - name: Notify On Failure
        if: ${{ failure() }}
        run: |
          $uri="${{ secrets.WEBHOOK }}"
          $body = @{
            "content" = ":construction_site: **Github Actions:** ${{ github.job }} failed :x: <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          } | ConvertTo-Json
          Invoke-RestMethod -Method Post -Uri $uri -ContentType "application/json" -Body $body

  build-docker:
    name: Build docker image
    runs-on: ubuntu-18.04
    environment: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Rotki Version
        id: rotki_version
        run: |
          ROTKI_VERSION=$(cat .bumpversion.cfg | grep 'current_version = ' | sed -n -e 's/current_version = //p')
          POSTFIX=$(if git describe --tags --exact-match "$REVISION" &>/dev/null; then echo ''; else echo '-dev'; fi)
          ROTKI_VERSION=${ROTKI_VERSION}${POSTFIX}-$(date +'%Y.%m.%d')
          echo "::set-output name=version::${ROTKI_VERSION}"
      - name: Build Information
        id: build_information
        run: |
          if [[ "$GITHUB_EVENT_NAME" == 'schedule' ]]; then
            PLATFORMS='linux/amd64,linux/arm64'
            TAG=nightly
          else
            PLATFORMS=linux/amd64
            TAG=dev
          fi
          echo "::set-output name=tag::$TAG"
          echo "::set-output name=platforms::$PLATFORMS"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ steps.build_information.outputs.platforms }}
          push: true
          tags: rotki/rotki:${{ steps.build_information.outputs.tag }}
          build-args: |
            REVISION=${{ github.sha }}
            ROTKI_VERSION=${{ steps.rotki_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Notify On Failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
            --url ${{ secrets.WEBHOOK }} \
            --header 'Content-Type: application/json' \
            --data '{
          	"content": ":construction_site: **Github Actions:** ${{ github.job }} failed :x: \r\n\r\n  <@&735068019440615516> please have a look at [${{ github.run_id }}](https://github.com/rotki/rotki/actions/runs/${{ github.run_id }}) :cry:"
          }'
